DEFAULT_SEKAI_LIVE2D_ASSET_BASE_URL = "https://storage.sekai.best/sekai-live2d-assets/live2d"

try:
    from .build_config import SEKAI_LIVE2D_ASSET_BASE_URL as _BUILD_SEKAI_LIVE2D_ASSET_BASE_URL
except ImportError:
    _BUILD_SEKAI_LIVE2D_ASSET_BASE_URL = DEFAULT_SEKAI_LIVE2D_ASSET_BASE_URL

SEKAI_LIVE2D_ASSET_BASE_URL = _BUILD_SEKAI_LIVE2D_ASSET_BASE_URL.rstrip("/")
