name: Build and Release

on:
  push:
    tags:
      - "v*"
    paths:
      - "app/**/*"
      - "resources/**/*"
      - "main.py"
      - "icon.ico"
      - "pyproject.toml"

  workflow_dispatch:

jobs:
  build:
    name: Build Executable
    strategy:
      fail-fast: false
      matrix:
#        os: [ macos-13, ubuntu-latest, windows-latest, macos-13-xl ]
        os: [ windows-latest ]
      max-parallel: 2
    defaults:
      run:
        shell: bash
    outputs:
      version: ${{ steps.set-version.outputs.VERSION }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry Action
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false

      - name: Install Dependencies
        run: |
          poetry install --with dev
          pip install imageio

      - name: Get Version
        id: set-version
        run: |
          echo "VERSION=$(poetry version -s)" >> $GITHUB_ENV

      - name: Build for macOS
        if: matrix.os == 'macos-13' || matrix.os == 'macos-13-xlarge'
        uses: Nuitka/Nuitka-Action@main
        with:
          script-name: 'main.py'
          mode: 'app'
          nuitka-version: 'main'
          enable-plugins: 'pyside6,tk-inter'
          windows-console-mode: 'attach'
          jobs: 10
          lto: 'yes'
          include-data-dir: "resources=resources"
          macos-app-icon: "app/resources/icons/logo.ico"
          file-version: ${{ env.VERSION }}

      - name: Build Windows or Linux
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'windows-latest'
        uses: Nuitka/Nuitka-Action@main
        with:
          script-name: 'main.py'
          mode: 'standalone'
          nuitka-version: 'main'
          enable-plugins: 'pyside6,tk-inter'
          windows-console-mode: 'attach'
          jobs: 10
          lto: 'yes'
          include-data-dir: "resources=resources"
          windows-icon-from-ico: "app/resources/icons/logo.ico"
          linux-icon: "app/resources/icons/logo.ico"
          file-version: ${{ env.VERSION }}

      - name: Zip files
        run: |
          7z a -t7z "MySekaiStorywriter-v${{ env.VERSION }}-${{ runner.os }}-${{ runner.arch }}.7z" "./build/main.dist/*" -mx=7 -m0=lzma2 -mmt=on 

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-build
          path: |
            *.7z
          if-no-files-found: error

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: build-artifacts
          merge-multiple: true

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          name: MySekaiStorywriter v${{ needs.build.outputs.version }}
          tag_name: v${{ needs.build.outputs.version }}
          files: build-artifacts/*